### PR TITLE
Allow custom endpoints to be used

### LINKED ISSUE #10: Allow custom endpoint to be used
We use Skylable to provide an S3-compatible local storage cluster, as we don't want to store our data in AWS. 

In order to use it instead of AWS, we need to be able to set a custom endpoint to use (rather than having it determined automatically).

### PR DESCRIPTION
**Pull request by jamieps**
Allow the endpoint to be customised, so that a local S3-compatible storage cluster can be used. If a custom endpoint is used, the region setting is ignored, fixes #10.

Currently, when using a custom endpoint Signature Version 4 is enforced.

### CODE REVIEW

**Comment by gschueler** [comment]
is the "Signature Version 4" a requirement? or just for your local S3-compatible storage service?

**Comment by jamieps** [comment]
It can be optional, depending on whether the storage service supports v4. I included it as it's recommended in the Skylable documentation.

If you'd prefer I can make that optional?

**Comment by gschueler** [comment]
@jamieps sure, i think that would be better. does it have to be a global setting?

**Comment by jamieps** [comment]
@gschueler I can't see any other way of doing it, unfortunately. I'll make the setting available regardless of whether the endpoint is custom, in case it's useful elsewhere.

**Comment by gschueler** [comment]
@jamieps sounds good

**Comment by jamieps** [comment]
@gschueler thanks, I've added a new property to control that separately

**Pull request merged**
